services:
  li_api:
    build:
      context: .
      dockerfile: serve.Dockerfile
    depends_on:
      - li_db
    # environment:
    #   NODE_ENV: local
    env_file: 
      - ./.env
    volumes:
      - type: bind
        source: ./public/user-images
        target: /app/public/user-images
    ports:
      - 3000:3000
    links: 
      - li_db
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: .
          target: /app
          action: sync

  li_db:
    image: mongo:4.2-bionic
    volumes: 
     - li-data:/data/db
    # ports:
    #   - 27017:27017

volumes:
  li-data:
    name: web_li-data